baseurl = "https://www.critiqus.com/"
disqusShortname = "thoughts-and-ideas-of-a-maker"
googleAnalytics = "UA-98300161-1"
languageCode = "en-us"
theme = "hugo-cactus-theme"
themesDir = "themes"
title = "Thoughts and ideas of a maker"
[params]
aboutauthor = "DevOps | Maker | Drone Enthusiast"
bio = "Make | Developer | DevOps"
copyright = ""
customcss = []
customjs = []
description = "Make | Developer | DevOps"
enablerss = true
home = ""
iconfont = "mono-social"
name = "Luis Morales"
newerposts = ""
olderposts = ""
readmore = ""
share = ""
socialiconstyle = "circle"
subscribe = ""
subtitle404 = ""
title404 = ""
tweet = "lacion"
twitter = "lacion"
[social]
github = "https://www.github.com/lacion"
instagram = "https://www.instagram.com/lacion/"
twitter = "https://www.twitter.com/lacion"
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
